#! /bin/sh

#pip install .

### Start the server ###

if [ $(curl -s http://127.0.0.1:4200/api -eq 0) ]; then
    echo "Prefect server already running"
else
    nohup prefect server start > autobfx_server_output.log 2>&1 &
    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
    echo "Prefect server started"
fi

### Start the default work pool with worker ###

# Check that the default pool exists and create it if it doesn't
if [ $(prefect work-pool ls | grep "default" | wc -l) -eq 0 ]; then
    prefect work-pool create --type process default
    echo "Default work pool created"
fi

nohup prefect worker start --pool default --name default-worker > autobfx_default_worker_output.log 2>&1 &
echo "Default worker started"