#! /bin/bash

echo "Careful! This script will stop ALL workers and the server. Check the dashboard and with anyone else running jobs through AutoBfx before doing this. Are you sure you want to continue? (y/n)"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo "Stopping all workers and the server..."
else
    echo "Exiting without stopping anything."
    exit 0
fi

### Stop the default work pool worker(s) ###

for pid in $(pgrep -f "prefect worker"); do
    kill $pid
done
sleep 1

### Stop the server ###

kill $(pgrep -f "prefect server")
sleep 1

### Check that everything has stopped ###

server_pid=$(pgrep -f "prefect server")
worker_pids=$(pgrep -f "prefect worker")

if [ -z "$server_pid" ]; then
    echo "Prefect server has stopped"
else
    echo "Prefect server is still running at PID $server_pid, try: 'kill -9 $server_pid'"
fi

if [ -z "$worker_pids" ]; then
    echo "All workers have stopped"
else
    echo "Workers are still running at PIDs $worker_pids, trying killing the processes manually with 'kill -9 ...'"
fi