name: Full Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  tests:
    name: Run Full Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: s-weigand/setup-conda@v1.2.3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Start Autobfx
        run: |
          bash cmd/start
          bash cmd/status

      - name: Run tests
        run: |
          pytest -s -vvvv -l --tb=long tests/e2e/