name: Full Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  tests:
    name: Run Full Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: s-weigand/setup-conda@v1.2.3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Start Autobfx
        run: |
          autobfx server start
          autobfx worker start --name default --work_pool default --type process

      - name: Run tests
        run: |
          pytest -s -vvvv -l --tb=long tests/e2e/

      - name: Dump logs
        run: |
          echo "Server logs"
          cat autobfx_server_output.err
          cat autobfx_server_output.log
          echo "Worker logs"
          cat autobfx_worker_default_default_output.err
          cat autobfx_worker_default_default_output.log