name: Tests

on:
  workflow_call:

  workflow_dispatch:

jobs:
  tests-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  tests:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.11', '3.10', '3.9']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest -s -vvvv -l --tb=long tests

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: pip install black

      - name: Lint Code Base
        run: |
          black --check .